RAN:
  gNB:
    gnb1:
      name: gnb1
      active: true
      new_terminal: false
      config_file: gnb1-{1,x,1,2}-{2,x,1,2}-{3,x,1,2}-{4,x,1,2}.yaml
OtherConfigs:
  BashCommands:
    pre:
      # - "echo teste 1"
    post:
      # - "echo teste 3"
